version: "3.7"
services:
  pocketbase:
    build:
      context: .
      args:
        - VERSION=0.22.22 # <--------- Set the Pocketbase version here. It will be downloaded from their GitHub repo
    container_name: pocketbase
    restart: unless-stopped

    ports:
      - "8090:8080"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations #optional
      - ./pb_hooks:/pb_hooks #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5